from pathlib import Path

path = Path('src/App.jsx')
text = path.read_text()
old = '''        {tab === 'expenses' && (\n          <div className="field compact-field">\n            <label htmlFor="paid-filter">Payment status</label>\n            <select id="paid-filter" value={paidFilter} onChange={(event) => setPaidFilter(event.target.value)}>\n              <option value="all">All</option>\n              <option value="paid">Paid</option>\n              <option value="unpaid">Unpaid</option>\n            </select>\n          </div>\n          <div className="field compact-field">\n            <label htmlFor="expense-class-filter">Expense type</label>\n            <select id="expense-class-filter" value={expenseClassFilter} onChange={(event) => setExpenseClassFilter(event.target.value)}>\n              <option value="all">All expenses</option>\n              <option value="fixed">Fixed bills</option>\n              <option value="variable">Variable spending</option>\n            </select>\n          </div>\n        )}'''
new = '''        {tab === 'expenses' && (\n          <>\n            <div className="field compact-field">\n              <label htmlFor="paid-filter">Payment status</label>\n              <select id="paid-filter" value={paidFilter} onChange={(event) => setPaidFilter(event.target.value)}>\n                <option value="all">All</option>\n                <option value="paid">Paid</option>\n                <option value="unpaid">Unpaid</option>\n              </select>\n            </div>\n            <div className="field compact-field">\n              <label htmlFor="expense-class-filter">Expense type</label>\n              <select id="expense-class-filter" value={expenseClassFilter} onChange={(event) => setExpenseClassFilter(event.target.value)}>\n                <option value="all">All expenses</option>\n                <option value="fixed">Fixed bills</option>\n                <option value="variable">Variable spending</option>\n              </select>\n            </div>\n          </>\n        )}'''
if old not in text:
    raise SystemExit('Generated Transactions filter block not found')
path.write_text(text.replace(old, new, 1))
print('Wrapped Transactions expense filters in a JSX fragment')
